# Generated by Django 4.1.13 on 2024-04-25 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TA', '0001_initial'),
        ('Student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='task',
            field=models.ManyToManyField(blank=True, to='TA.task'),
        ),
    ]
