# Generated by Django 4.1.13 on 2024-04-25 23:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TA', '0001_initial'),
        ('Student', '0002_studentprofile_task'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='task',
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='TA.task'),
        ),
    ]
