# Generated by Django 4.1.13 on 2024-04-25 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TA', '0001_initial'),
        ('Student', '0003_remove_studentprofile_task_studentprofile_task'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='task',
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='tasks',
            field=models.ManyToManyField(blank=True, to='TA.task'),
        ),
    ]
