# Generated by Django 4.1.13 on 2024-04-25 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0004_remove_studentprofile_task_studentprofile_tasks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='badge',
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='badge',
            field=models.ManyToManyField(blank=True, null=True, to='Student.badge'),
        ),
    ]
