# Generated by Django 4.1.13 on 2024-04-25 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0005_remove_studentprofile_badge_studentprofile_badge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='badge',
            field=models.ManyToManyField(blank=True, to='Student.badge'),
        ),
    ]
