# Generated by Django 4.1.13 on 2024-04-30 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0008_alter_studentprofile_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='refreshtoken',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
