# Generated by Django 4.1.13 on 2024-05-01 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0010_extra'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentprofile',
            options={},
        ),
        migrations.AlterModelManagers(
            name='studentprofile',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='user_permissions',
        ),
    ]
