# Generated by Django 4.1.13 on 2024-05-02 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0011_alter_studentprofile_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='refreshtoken',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
