# Generated by Django 4.1.13 on 2024-05-02 19:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('TA', '0004_alter_instructorprofile_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Extra_TA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faculty', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='TA.instructorprofile')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
